name: Alerta Plan de Trabajo SST

on:
  schedule:
    - cron: "0 12 15 * *"
    - cron: "0 12 28-31 * *"

  workflow_dispatch:

jobs:
  alerta:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests

      - name: Probar descarga con curl
        run: |
          curl -I "https://valserindustriales-my.sharepoint.com/personal/tecnicodeservicios_valserindustriales_com/_layouts/15/download.aspx?UniqueId=4bd45590%2D7a3a%2D4e97%2D8947%2D91feabaa0373"
          
      - name: Ejecutar alerta
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EXCEL_URL: ${{ secrets.EXCEL_URL }}
        run: python alerta_plan_trabajo.py
